### ISSUE TITLE
The public/nuget-public groups requires authentication by default when browsing

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#562] opened 2018-02-02 17:45 UTC
The `public:nuget-public` repository currently pops up an authentication window when trying to browse. This should not be so and it should be possible to browse this group repository, unless it's specifically configured otherwise.

Relates to #496.

**Comment by carlspring** [comment] 2018-02-02 17:45
@sanket407 ,

Any idea why this is happening?

**Comment by sanket407** [comment] 2018-02-03 05:57
@carlspring yes this is something specifically implemented by @sbespalov  in the NugetArtifactController when a GET request comes for a repository. Check the method called 'greet()'. Also our current master has no support for Nuget Browsing. Only Maven and Raw browsing is supported.

**Comment by sbespalov** [comment] 2018-03-06 04:44
@carlspring @steve-todorov I think this should go away since we moved to `browse` URL prefix for browsing.
@steve-todorov can you please check this in current master?

**Comment by steve-todorov** [comment] 2018-03-06 05:06
@sbespalov I'll have a look later today :)

**Comment by steve-todorov** [comment] 2018-03-06 23:39
@sbespalov  There seems to be an issue with the URL for the public nuget repo as well as other repos:

http://strongbox-snapshot.carlspring.org/api/browse/public/nuget.org/
http://strongbox-snapshot.carlspring.org/api/browse/public/carlspring/

Is this a bug or I got the wrong links?

**Comment by sbespalov** [comment] 2018-03-07 01:26
yes, probably it is a bug :)

**Comment by sbespalov** [comment] 2018-03-07 01:27
it worked before moving under `api` prefix

**Comment by carlspring** [comment] 2018-03-07 02:17
Shouldn't the link for browsing be `/storages/${storageId}/${repositoryId}/...`?

**Comment by sbespalov** [comment] 2018-03-07 02:18
> Shouldn't the link for browsing be http://localhost:48080/storages/${storageId}/${repositoryId}/...?

currently we agreed to use `browse` prefix instead of `storages` for browsing

**Comment by carlspring** [comment] 2018-03-07 02:18
@sbespalov,

Please, remember that as stated by our Windows guru (@fuss86) "There are no bugs in Strongbox".

**Comment by carlspring** [comment] 2018-03-07 02:22
>> Shouldn't the link for browsing be http://localhost:48080/storages/${storageId}/${repositoryId}/...?

> currently we agreed to use `browse` prefix instead of `storages` for browsing

Ah, yeah, I forgot this was a temporary solution.
So... this no longer works after the API URL refactoring?

**Comment by sbespalov** [comment] 2018-03-07 02:23
I will take a look

**Comment by sbespalov** [comment] 2018-03-07 10:00
> Please, remember that as stated by our Windows guru (@fuss86) "There are no bugs in Strongbox".

@carlspring I want to say that you was defenetely right here, because it's not a bug... IT'S A FEATURE!!! :sweat_smile:

the issue is that `public` is group repository and browsing currently not support group repositories. :simple_smile:

**Comment by sbespalov** [comment] 2018-03-07 10:11
https://github.com/strongbox/strongbox/pull/631

fixed

**Comment by carlspring** [comment] 2018-03-07 21:34
@sbespalov , I've merged it. So, we can close this issue now?

**Comment by sbespalov** [comment] 2018-03-08 01:27
@steve-todorov  you approve that its work?

чт, 8 мар. 2018 г., 4:34 Martin Todorov <notifications@github.com>:

**Comment by steve-todorov** [comment] 2018-03-12 00:42
Sorry for the delay. Yes it appears it's working now. I believe we can close this. :)

**Comment by carlspring** [comment] 2018-03-28 02:24
Thanks! :)

**Closed** 2018-03-28 02:24 UTC
Labels: bug, good first issue, help wanted
