### ISSUE TITLE
Investigate random test failures with the MavenMetadataExpirationMultipleGroupCaseTest

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1101] opened 2019-03-10 23:25 UTC
# Task Description

We are getting the following randomly occurring test failure:

```
Building / expiredGroupMetadataShouldFetchVersionLevelMetadataFromFirstMatch{TestInfo} – org.carlspring.strongbox.providers.io.MavenMetadataExpirationMultipleGroupCaseTest

Error
Input length = 1
Stacktrace
java.nio.charset.MalformedInputException: Input length = 1
at org.carlspring.strongbox.providers.io.MavenMetadataExpirationMultipleGroupCaseTest.expiredGroupMetadataShouldFetchVersionLevelMetadataFromFirstMatch(MavenMetadataExpirationMultipleGroupCaseTest.java:167)
```

We need to investigate and fix this.

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by prbobba** [comment] 2019-03-12 06:01
I will take a look at this.

**Comment by carlspring** [comment] 2019-03-12 08:39
Okay, thanks! :)

**Comment by prbobba** [comment] 2019-03-13 14:12
I have run this test about 100 times from IntelliJ (Windows 8, Java 1.8.181). Also ran this 25 times from the command line (Ubuntu 18) using `mvn clean install -Dintegration.tests -s ~/.m2/stronsettings.xml`. It didn't fail once. 

![Clipboard - March 12, 2019 11_54 AM](https://user-images.githubusercontent.com/14883250/54285288-ac1e8300-45c7-11e9-99b8-2db39cd1332e.png)

What we can do is to add more logging so that, when it fails we may know the root cause.

**Comment by matevarga** [comment] 2019-03-18 17:36
Guys, this and #1097 both look like concurrency issues -- the test is marked with CONCURRENT so there's a threadpool executing the threads but the test methods are not pure functions, they mutate shared state. Just my 2c.

**Comment by carlspring** [comment] 2019-03-18 17:42
@matevarga ,

Would you like to have a look at the code and investigate it further? Also, please feel free to join our 
[chat channel](https://chat.carlspring.org/).

**Comment by symposion** [comment] 2019-03-20 17:23
It's worth noting that, for me, at any rate, this test can be made to fail locally a lot more regularly by changing the junit.jupiter.execution.parallel.config.fixed.parallelism value in junit-platform.properties to e.g. 4 (I'm on a quad-core machine) Various different tests start failing at this point in non-deterministic ways. I haven't seen the exact error listed on this ticket but I do get a number of other failures with MavenMetadataExpirationMultipleGroupCaseTest. For example:

`MavenMetadataExpirationMultipleGroupCaseTest.expiredGroupMetadataShouldFetchVersionLevelMetadataFromFirstMatch:168 expected: <83bfcfec1744ef0b961a4075a353aa3c60fa1b39> but was: <9feb4542edc50aaa2da3a2cfbef70cdcfd75f7fd>`

**Comment by carlspring** [comment] 2019-04-02 23:32
This seems to still be happening randomly. Would anybody like to further investigate it?

We're seeing this randomly in our Jenkins:
```
Error Message
expected: <964ef9ad68aa229537ad1ff0abd821f239f7b0b8> but was: <e2cf6440a4bbc601fb9fef2ecfd9589ca74f83a0>
Stacktrace
org.opentest4j.AssertionFailedError: expected: <964ef9ad68aa229537ad1ff0abd821f239f7b0b8> but was: <e2cf6440a4bbc601fb9fef2ecfd9589ca74f83a0>
	at org.carlspring.strongbox.providers.io.MavenMetadataExpirationMultipleGroupCaseTest.expiredGroupMetadataShouldFetchVersionLevelMetadataFromFirstMatch(MavenMetadataExpirationMultipleGroupCaseTest.java:172)
```

**Comment by carlspring** [comment] 2019-08-14 02:16
@ptirador : This is probably now obsolete. Please, feel freel to close it, if you think it's working fine now.

Thanks! :)

**Comment by ptirador** [comment] 2019-08-14 11:13
@carlspring: Currently this test class is working fine, without any random failure.
I proceed to close it.

**Closed by ptirador** 2019-08-14 11:13 UTC
Labels: bug, good first issue, help wanted, testing

**Comment by carlspring** [comment] 2019-08-14 11:18
Thank you!
