### ISSUE TITLE
Investigate why the ArtifactManagementServiceImplTest is failing

### ISSUE THREAD

**Issue by carlspring** [strongbox/strongbox#1248] opened 2019-04-23 23:49 UTC
# Task Description

We've had to disable the `ArtifactManagementServiceImplTest`, as a follow-up to #1246. We need to re-enable this test and resolve it's issues with high priority. This test needs to be re-worked to use the new test annotations, as explained in #1165. Once the test is re-enabled, it should start failing in our Travis build, as Travis is building the code under MacOS, where it seems to almost always be reproducible.

# Acceptance Test

* [ ] Building the code with `mvn clean install -Dintegration.tests` still works.
* [ ] Running `mvn spring-boot:run` in the `strongbox-web-core` still starts up the application correctly.
* [ ] Building the code and running the `strongbox-distribution` from a `zip` or `tar.gz` still works.
* [ ] The tests in the [`strongbox-web-integration-tests`](https://github.com/strongbox/strongbox-web-integration-tests/) still run properly.

# Task Relationships

This task:
* Is a sub-task of: #1165 
* Is a follow-up of: #1246
* Relates to: #1101 , #1243 , #1165

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by yugander-krishan-singh** [comment] 2019-04-25 16:02
@carlspring I was able to reproduce the test failure in `ArtifactManagementServiceImplTest` class. And investigated the cause of failure of `ArtifactManagementServiceImplTest.testConcurrentReadWrite`.
 
As per my understanding this test is failing due to multiple race condition occurring between different threads in the following piece of code(`getResult()` inside `ArtifactManagementServiceImplTest `class)-  
```
return aBoolean.getAndSet(!aBoolean.get()) ?
                   new Store(new ByteArrayInputStream(loremIpsumContentArray[i / 2]), repository, path).call() :
                   new Fetch(repository, path).call();
```

here the first race condition occurs in `aBoolean.getAndSet(!aBoolean.get())`. This expression has two individual actions here, each, separately (!aBoolean.get() and aBoolean.getAndSet) are atomic; combined they are not. this is also called the anti-pattern "check than act".

And the second race condition is occurring in `new Store(new ByteArrayInputStream(loremIpsumContentArray[i / 2]), repository, path).call() ` and `new Fetch(repository, path).call();`. 

As per my understanding the getResult() is supposed to do two things. first `aBoolean `is true so it stores the artifact by calling `new Store().call()` and it sets the `aBoolean `to false now which means next time it is supposed to call `new Fetch().call()` which means artifact is fetched. And again this is repeated as aBoolean alternates between true and false;

But due to use of parallel streams multiple threads can be there in `getResult `function at a time. I have tested this by putting print statements inside `getResult `and I can see multiple times `aBoolean `printed as true which means multiple threads are there in `getResult `and therefore a race exists.

But this race is not causing the issue. The issue is when a thread which is storing the artifcat by calling new Store().call and on the same time there is a different thread which is calling new Fetch().call trying to fetch the same artifact. Now if second thread wins the race then it means it will try to fetch the artifact which doesn't exist and we will see an `ArtifactNotFoundException` in the logs. I have found out the same exception in stack trace.

Now in my opinion in order to make this test pass we need to synchronize the access to both` new Store().call() and new Fetch().call()`. For this I created a lock instance and passed the same to both the call functions of `Store `and `Fetch `class. Once I did this I ran the `ArtifactManagementServiceImplTest` a number of times and I can see the test passing all the times.

**Comment by carlspring** [comment] 2019-04-25 16:36
@yugander-krishan-singh : Thanks for your extensive investigation and detailed description of the problem.

@fuss86 : Would you mind reviewing?

**Comment by fuss86** [comment] 2019-04-25 22:45
Hi @yugander-krishan-singh,

thank you for deep investigation, but unfortunately it does not highlight the real issue here. 

The idea of this test is to ensure that N threads are able to store/read to/from the same location. 

 > This expression has two individual actions here, each, separately (!aBoolean.get() and aBoolean.getAndSet) are atomic; combined they are not. this is also called the anti-pattern check than act.

I agree with you that these 2 operations are not atomic together. Expression `aBoolean.getAndSet(!aBoolean.get())` provides some kind of randomness, that's fine. But we can be sure about one thing, it will *always* return `true` by the first `Thread` because we initialized it by `new AtomicBoolean(true)`. So we know that `new Store(...)` will be called at least once (however, we can't be sure whether it will be the first action or not). 

`NullPointerException` encountered during this test shouldn't be "fixed" [this way you proposed](https://github.com/strongbox/strongbox/pull/1250/files#diff-a0ca838f38a43fbc4b2b2c83bf4b1fb5R571). This exception occurred because we did something wrong in the core code, not in the test. This test could fail (yes, there is a probability if fetching threads have been waiting too long for storing thread), but exception from the core code signals some real problems.

@carlspring , @sbespalov the issue here is:
we are opening `TempOutputStream` based on `TempRepositoryPath` before writing and then we are trying to lock the `path` (let's say by `Thread A`). If this `path` is currently locked by some other `Thread B`, the content from the `TempRepositoryPath` will be moved to the target destination by `Thread B`, and `TempRepositoryPath` will be deleted. When the `Thread B` releases the `path` lock, `Thread A` acquires it and it wants to operate on non-existing `TempRepositoryPath` (because this path was deleted by `Thread B`) having opened `TempOutputStream` . This needs to be fixed in the core code.

**Comment by yugander-krishan-singh** [comment] 2019-04-26 06:15
@fuss86 Thanks for the explanation. 
@carlspring I will remove the changes made and update the PR.

**Comment by sbespalov** [comment] 2019-05-06 09:41
The initial implementation of `ArtifactManagementServiceImplTest.getResult` condition was the `i % 2 == 0`, to have same number of reads and writes, unlike of `aBoolean.getAndSet(!aBoolean.get())` which seems really not thread safe and makes test results more unpredictable.

Anyway, is there any stack trace for this random `ArtifactManagementServiceImplTest.testConcurrentReadWrite` failures?

**Comment by sbespalov** [comment] 2019-05-06 10:10
> @carlspring , @sbespalov the issue here is:

@fuss86  thanks for explanation, actually I thought that this case should work fine because we start writing only after lock accrued by writer thread, but maybe you right and we should have a test for it.

@carlspring  I will do the unit test for the above scenario, and try to fix it if there will be any issues with it.

**Comment by carlspring** [comment] 2019-05-06 10:15
Okay, thanks for looking into it, @sbespalov ! :)

**Comment by fuss86** [comment] 2019-05-07 19:32
> The initial implementation of ArtifactManagementServiceImplTest.getResult condition was the i % 2 == 0, to have same number of reads and writes, 

Yes, but it failed many times because `new Fetch` Threads were able to be called many times before `new Store` Threads

> unlike of aBoolean.getAndSet(!aBoolean.get()) which seems really not thread safe 

it's not meant to be thread safe but ensure `new Store` is called by the first Thread

> and makes test results more unpredictable.

it brings more randomness in the number of `new Store`/`new Fetch` operations

> Anyway, is there any stack trace for this random ArtifactManagementServiceImplTest.testConcurrentReadWrite failures?

It's easily reproducible on my end. [Here is the gist](https://gist.github.com/fuss86/0cff07f190fc171452c431ab0451be87).

I can make logs more verbose for you, if you want.

**Comment by sbespalov** [comment] 2019-05-15 01:16
I also found a deadlock within this task 
[thread dump](https://gist.github.com/sbespalov/b92ad29b9b4ec2fd6256be6dca455ec8)

**Closed** 2019-05-29 10:51 UTC
Labels: good first issue, help wanted, in progress, testing
