### ISSUE TITLE
Test failures strongbox-web-core on Windows 10

### ISSUE THREAD

**Issue by denizseaside82** [strongbox/strongbox#1140] opened 2019-03-21 12:57 UTC
# Task Description

After following "Getting Started" section on developer gulde page, proceeding with "mvn clean install" causes an errror like in the following.

My Enviroment: 
Maven 3.5.4
JDK 1.8

Error message:
```
Test set: org.carlspring.strongbox.controllers.JwtAuthenticationTest
Tests run: 4, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 5.361 s <<< FAILURE! - in 
org.carlspring.strongbox.controllers.JwtAuthenticationTest
testJWTAuthShouldFailWithoutToken Time elapsed: 0.202 s <<< FAILURE!
java.lang.AssertionError:
1 expectation failed.
JSON path error doesn’t match.
Expected: Full authentication is required to access this resource
at org.carlspring.strongbox.controllers.JwtAuthenticationTest.testJWTAuthShouldFailWithoutToken(JwtAuthenticationTest.java:97)
```

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @sbespalov
  * @fuss86

**Comment by adavid9** [comment] 2019-03-21 18:51
@denizseaside82 I've also `Windows 10` with the same `maven` and `jdk` and I can not reproduce this issue.

**Comment by carlspring** [comment] 2019-03-21 23:30
@denizseaside82 ,

Do you have any other local modifications? Is this the latest version of the code? Which revision is it?

**Comment by denizseaside82** [comment] 2019-04-01 20:44
Hi Martin, Sorry for late answer. I have no local modification. I just followed installing instructions. I hope ,you mean with revision in the following;
    <parent>
        <groupId>org.carlspring.strongbox</groupId>
        <artifactId>strongbox-parent</artifactId>
        <version>1.0-SNAPSHOT</version>
        <relativePath/>
    </parent>

**Comment by carlspring** [comment] 2019-04-01 21:12
Is it still failing?

**Comment by carlspring** [comment] 2019-04-02 11:46
Closing this issue, as it seems to be due to old hardware (the machine running it is around 10 years old -- not the best environment to build the code).

**Closed by carlspring** 2019-04-02 11:46 UTC
Labels: good first issue, help wanted, testing
