### ISSUE TITLE
Cannot use choco list on nuget repositories

### ISSUE THREAD

**Issue by gretel** [strongbox/strongbox#1662] opened 2020-01-30 10:51 UTC
# Bug Description

The default configuration has `ANONYMOUS_ROLE` set but trying to browse a nuget directory does always require authentication.

# Steps To Reproduce

1. Deploy strongbox using default configuration
2. Enable "Allow directory browsing" in `nuget-storage`
3. Try to do any `api` transaction anonomously (like `choco list`)

# Expected Behavior

Anonoymous users should be able to browse the directory as inherited by `ARTIFACTS_RESOLVE`

# Environment

* Strongbox Version: `{"strongbox":{"version":"1.0-SNAPSHOT","revision":"eccd13064b1e3bfa"}}`
* OS: `adoptopenjdk/openjdk8:jdk8u232-b09-alpine`

**Comment by steve-todorov** [comment] 2020-01-30 12:17
These might be two different problems. Are you talking about `choco list` or about browsing `/api/browse/storage/nuget-repository` ?

**Comment by gretel** [comment] 2020-01-30 12:20
@steve-todorov `choco list` should be possible anonymously.

**Comment by anki2189** [comment] 2020-02-06 10:21
@gretel : Please share source used for command  `choco list ` .

**Comment by gretel** [comment] 2020-02-06 10:45
```
choco source add --name=chocobox --source=$internalRepositoryLocation --user=$internalRepositoryUser --password=$internalRepositoryScrt --priority=1 --bypass-proxy
```

**Comment by anki2189** [comment] 2020-02-06 17:34
There is a method in NugetArtifactController `NugetArtifactController#greet()` which is used to 
 check storage availability. 
This method requires `ARTIFACTS_DEPLOY` role , hence `choco list` or `nuget list` command prompt for authentication.

Issue can be fixed by changing `ARTIFACTS_DEPLOY` to `ARTIFACTS_RESOLVE` or by removing  auth from greet() method.

**Comment by carlspring** [comment] 2020-02-06 19:38
The `greet` method is absolutely useless and can be removed. Will that solve your problem altogether? :-D

**Comment by gretel** [comment] 2020-02-06 19:40
i guess i would solve mine, too :)

**Comment by steve-todorov** [comment] 2020-02-06 19:42
There's actually a comment for this in the code - the `greet` method is necessary because Nuget will ping it to determine if the repository is healthy or not. In this case we should probably use `ARTIFACTS_RESOLVE` for this case.

**Comment by carlspring** [comment] 2020-02-06 19:44
Upon closer look this is actually doing something. We used to have these `greet` methods long before we migrated to restassured and Spring Boot which were purely for testing purposes and should have been removed a long time ago. Perhaps it would be better to rename the method to something more meaningful...(?)

**Comment by gretel** [comment] 2020-02-06 19:46
btw, `repository is healthy or not` - how is this determined?

**Comment by sbespalov** [comment] 2020-02-07 01:24
> There's actually a comment for this in the code - the greet method is necessary because Nuget will ping it to determine if the repository is healthy or not. In this case we should probably use ARTIFACTS_RESOLVE for this case.

this comment also say that Nuget using this method to check that authentication required. AFAIK it will fail to deploy with `ARTIFACTS_RESOLVE` on this method.

**Comment by sbespalov** [comment] 2020-02-07 01:39
@anki2189 can you please check it with Nuget v2 and v3? Also from your previous comment it's become unclear how choco determines the need for authentication?

**Comment by anki2189** [comment] 2020-02-07 04:10
`choco list` command fails after trying multiple times.

`choco list -Source http://192.168.1.2:48080/storages/storage-nuget/nuget-releases/`
```
Invalid credentials specified.
Invalid credentials specified.
Invalid credentials specified.
Invalid credentials specified.
Invalid credentials specified.
Invalid credentials specified.
Invalid credentials specified.
Invalid credentials specified.
[NuGet] Not able to contact source 'http://192.168.1.2:48080/storages/storage-nuget/nuget-releases/'. Error was The remote server returned an error: (401) Unauthorized.
Invalid credentials specified.
Invalid credentials specified.
Invalid credentials specified.
Invalid credentials specified.
Invalid credentials specified.
Invalid credentials specified.
Invalid credentials specified.
Invalid credentials specified.
[NuGet] Not able to contact source 'http://192.168.1.2:48080/storages/storage-nuget/nuget-releases/'. Error was The remote server returned an error: (401) Unauthorized.
0 packages found.
```

Whereas `nuget list` prompts for username.
```
nuget list  -Source  http://localhost:48080/storages/storage-nuget/nuget-releases/              
Please provide credentials for: http://localhost:48080/storages/storage-nuget/nuget-releases/
UserName: 
```

**Comment by anki2189** [comment] 2020-02-07 04:17
> @anki2189 can you please check it with Nuget v2 and v3 and latest mono? Also from your previous comment it's become unclear how choco determines the need for authentication?

Behaviour  is same using both nuget 2 and 3 exe.

`NuGet Version: 2.8.60717.93`

`NuGet Version: 3.5.0.1938`

```
Mono JIT compiler version 6.4.0.198 (2019-06/fe64a4765e6 Wed Sep 18 14:14:51 EDT 2019)
Copyright (C) 2002-2014 Novell, Inc, Xamarin Inc and Contributors. www.mono-project.com
	TLS:           
	SIGSEGV:       altstack
	Notification:  kqueue
	Architecture:  amd64
	Disabled:      none
	Misc:          softdebug 
	Interpreter:   yes
	LLVM:          yes(610)
	Suspend:       hybrid
	GC:            sgen (concurrent by default)
```

**Comment by sbespalov** [comment] 2020-02-07 07:15
@anki2189 why `choco` fails with `Invalid credentials specified.`? Does it send any credentials?

**Comment by sbespalov** [comment] 2020-02-07 07:37
I mean that we should find the root cause of why `choco` is not request the authentication like Nuget. Maybe it expect another Authentication Entry Point or send Authentication which is not supported by strongbox.

**Comment by anki2189** [comment] 2020-02-07 15:51
> @anki2189 why `choco` fails with `Invalid credentials specified.`? Does it send any credentials?

From documentation it doesn't . https://github.com/chocolatey/choco/wiki/CommandsList

**Comment by gretel** [comment] 2020-02-07 16:18
`choco` can send credentials on each command, this is how i work around this issue currently.

**Comment by anki2189** [comment] 2020-02-07 16:26
> I mean that we should find the root cause of why `choco` is not request the authentication like Nuget. Maybe it expect another Authentication Entry Point or send Authentication which is not supported by strongbox.



> `choco` can send credentials on each command, this is how i work around this issue currently.

By default it assumes username to be empty it not provided.

**Comment by anki2189** [comment] 2020-02-07 16:27
Also there is no Authorization header in request for `choco list` command.

**Comment by anki2189** [comment] 2020-02-07 16:29
> `choco` can send credentials on each command, this is how i work around this issue currently.

By default it assumes username to be empty it not provided.

**Comment by sbespalov** [comment] 2020-02-08 11:39
> By default it assumes username to be empty it not provided.

@anki2189 does it requests the authentication for `push` command?

**Comment by anki2189** [comment] 2020-02-08 14:04
> > By default it assumes username to be empty it not provided.
> 
> @anki2189 does it requests the authentication for `push` command?

Only api-key

**Comment by anki2189** [comment] 2020-02-08 14:43
> > By default it assumes username to be empty it not provided.
> 
> @anki2189 does it requests the authentication for `push` command?

Yes, api-key

**Comment by sbespalov** [comment] 2020-02-10 02:26
ok, let's try  `@PreAuthorize("hasAuthority('ARTIFACTS_RESOLVE')")` then for `greet`. @anki2189 can you pelase check how Nuget `push` and `list` will work with it?

**Comment by sbespalov** [comment] 2020-02-11 04:19
PR #1674 seems works fine, so I suggest to merge it and resolve the issue. Just to be clear regarding 
the `ARTIFACTS_DEPLOY` authority which we had on `greet` method before then it probably was needed when there was no API Key authentication implemented. So since we have the  API Key authentication `ARTIFACTS_RESOLVE` seems works fine as well.

**Closed** 2020-02-11 09:28 UTC
Labels: bug, help wanted

**Comment by carlspring** [comment] 2020-02-11 09:37
@gretel : Could you please test this out?

**Comment by gretel** [comment] 2020-02-11 19:17
@carlspring the pipeline eats the github snapshot.. dont have any maven running :(

**Comment by carlspring** [comment] 2020-02-11 19:32
@steve-todorov : Could you please take a look? Thanks!

**Comment by steve-todorov** [comment] 2020-02-11 19:39
It's already in the `master` and on github as `1.0-SNAPSHOT`. You can download the compiled version from there.

**Comment by gretel** [comment] 2020-02-11 19:40
@steve-todorov ah i didnt notice the merge. can bump the deployment tomorrow. regards
