### ISSUE TITLE
Fix  RegenerateNugetChecksumCronJobTestIT test

### ISSUE THREAD

**Issue by sbespalov** [strongbox/strongbox#1741] opened 2020-04-13 04:29 UTC
# Task Description

We need to fix this test against the `issues/1649` branch.

Example Jenkins build [here](https://jenkins.carlspring.org/blue/organizations/jenkins/strongbox%2Fbuilds%2Fstrongbox/detail/PR-1676/105/tests).

This is most likely due to concurrent execution and you may not always get this result locally.

Stack trace:
```
09:03:56.150 09-04-2020 | ERROR | kJoinPool-1-worker-1 | o.c.s.t.storage.repository.TestRepositoryContext   | Failed to close [TestRepository] with id [storage-nuget-rncc-trnac/repository-rnccjt-trnac] 
java.io.IOException: org.carlspring.strongbox.checksum-second.nuspec.sha512
org.carlspring.strongbox.checksum-second.1.0.0.nupkg.sha512
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider$3.postVisitDirectory(StorageFileSystemProvider.java:262)
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider$3.postVisitDirectory(StorageFileSystemProvider.java:229)
	at java.nio.file.Files.walkFileTree(Files.java:2688)
	at java.nio.file.Files.walkFileTree(Files.java:2742)
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider.recursiveDeleteExceptRoot(StorageFileSystemProvider.java:228)
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider.delete(StorageFileSystemProvider.java:206)
	at org.carlspring.strongbox.providers.layout.LayoutFileSystemProvider.delete(LayoutFileSystemProvider.java:262)
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider.delete(StorageFileSystemProvider.java:178)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.carlspring.strongbox.repository.AbstractRepositoryManagementStrategy.removeDirectoryStructure(AbstractRepositoryManagementStrategy.java:99)
	at org.carlspring.strongbox.repository.AbstractRepositoryManagementStrategy.removeRepository(AbstractRepositoryManagementStrategy.java:85)
	at org.carlspring.strongbox.services.impl.RepositoryManagementServiceImpl.removeRepository(RepositoryManagementServiceImpl.java:103)
	at org.carlspring.strongbox.testing.storage.repository.TestRepositoryContext.closeInternal(TestRepositoryContext.java:268)
	at org.carlspring.strongbox.testing.storage.repository.TestRepositoryContext.close(TestRepositoryContext.java:239)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeDestroyMethods(InitDestroyAnnotationBeanPostProcessor.java:347)
	at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeDestruction(InitDestroyAnnotationBeanPostProcessor.java:177)
	at org.springframework.beans.factory.support.DisposableBeanAdapter.destroy(DisposableBeanAdapter.java:242)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroyBean(DefaultSingletonBeanRegistry.java:571)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingleton(DefaultSingletonBeanRegistry.java:543)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingleton(DefaultListableBeanFactory.java:1072)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.destroySingletons(DefaultSingletonBeanRegistry.java:504)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.destroySingletons(DefaultListableBeanFactory.java:1065)
	at org.springframework.context.support.AbstractApplicationContext.destroyBeans(AbstractApplicationContext.java:1060)
	at org.springframework.context.support.AbstractApplicationContext.doClose(AbstractApplicationContext.java:1029)
	at org.springframework.context.support.AbstractApplicationContext.close(AbstractApplicationContext.java:978)
	at org.carlspring.strongbox.testing.storage.repository.TestRepositoryManagementApplicationContext.close(TestRepositoryManagementApplicationContext.java:274)
	at org.carlspring.strongbox.testing.storage.repository.TestRepositoryManagementApplicationContext.closeExtension(TestRepositoryManagementApplicationContext.java:103)
	at org.carlspring.strongbox.testing.storage.repository.TestRepositoryManagementContextSupport.afterTestExecution(TestRepositoryManagementContextSupport.java:44)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAfterTestExecutionCallbacks$8(TestMethodTestDescriptor.java:220)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeAllAfterMethodsOrCallbacks$14(TestMethodTestDescriptor.java:245)
	at java.util.ArrayList.forEach(ArrayList.java:1257)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAllAfterMethodsOrCallbacks(TestMethodTestDescriptor.java:243)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeAfterTestExecutionCallbacks(TestMethodTestDescriptor.java:219)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:129)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:68)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:135)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinTask.doJoin(ForkJoinTask.java:389)
	at java.util.concurrent.ForkJoinTask.join(ForkJoinTask.java:719)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.joinConcurrentTasksInReverseOrderToEnableWorkStealing(ForkJoinPoolHierarchicalTestExecutorService.java:148)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService.invokeAll(ForkJoinPoolHierarchicalTestExecutorService.java:115)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$5(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$7(NodeTestTask.java:125)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:135)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:123)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:122)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:80)
	at org.junit.platform.engine.support.hierarchical.ForkJoinPoolHierarchicalTestExecutorService$ExclusiveTask.compute(ForkJoinPoolHierarchicalTestExecutorService.java:171)
	at java.util.concurrent.RecursiveAction.exec(RecursiveAction.java:189)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
Caused by: java.nio.file.DirectoryNotEmptyException: /home/jenkins/agent/workspace/rongbox_builds_strongbox_PR-1676/linux/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/target/strongbox-vault/storages/storage-nuget-rncc-trnac/repository-rnccjt-trnac/org.carlspring.strongbox.checksum-second/1.0.0
	at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
	at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
	at java.nio.file.Files.delete(Files.java:1126)
	at org.carlspring.strongbox.providers.io.StorageFileSystemProvider$3.postVisitDirectory(StorageFileSystemProvider.java:253)
	... 79 common frames omitted
```
# How to fix

We should extract the `RegenerateNugetChecksumCronJobTestIT.testRegenerateNugetChecksumInStorages` test method into dedicated test class with ovverriden `strongbox.vault` property. With Spring Boot it could be done using `@SpringBootTest(properties = { "strongbox.vault=${strongbox.basedir}/strongbox-vault-rnccjt" })`

# Task Relationships

This task:
* Is a sub-task of: #1649

# Help

* [Our chat](https://chat.carlspring.org/)
* Points of contact:
  * @carlspring
  * @fuss86
  * @sbespalov
  * @steve-todorov

**Comment by valiobojinov** [comment] 2020-04-13 10:17
I'm currently investigating this one, please assign to me:
So far
It is locally reproducible by: mvn  -Dtest=RegenerateNugetChecksumCronJobTestIT -Djunit.jupiter.execution.parallel.enabled=true  -Djunit.jupiter.execution.parallel.mode.default=concurrent test
The test sometimes passes but when it fails it is because either one of 

- strongbox/strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/target/strongbox-vault/storages/storage-nuget-rncc-trnac/repository-rnccjt-trnac/org.carlspring.strongbox.checksum-second/1.0.0/org.carlspring.strongbox.checksum-second.nuspec.sha512 

- strongbox-storage/strongbox-storage-layout-providers/strongbox-storage-nuget-layout-provider/target/strongbox-vault/storages/storage-nuget-rncc-trncis/repository-rnccjt-trncis/org.carlspring.strongbox.checksum-second/1.0.0/org.carlspring.strongbox.checksum-second.nuspec.sha512 

remain in the target directory thus it can't be cleanup at test end, leading  the DirectoryNotEmpty failing the test at cleanup after execution, I am currently tail -F to follow when those files appear. I've seen that there are few Files.delete surrounded within Files.exists which for nio operations doesn't make much sense, but I also suspect misssync in the chronjob resulting in a file getting generated later than expected.  I'll keep this one updated

**Comment by sbespalov** [comment] 2020-05-04 03:41
the problem seems related with `testRegenerateNugetChecksumInStorages` test method because it affects on all storages and as a result it goes out of `@NugetRepository` sychronozation. The proposed solution added to the issue description.

**Comment by valiobojinov** [comment] 2020-05-04 16:52
I've been trying to reverse engineer the annotations based synchronization, not really successfully.- Where I bumped seriously I guess is: TestRepositoryContext#closeInternal - the bit where RepositoryManagementService#removeRepository - gets closed twice if for the annotations that return cleanup -> true; but that is since the initial version.
  I've seen in the history - that at some point the test had been annotated with @Transactional but the commit that has removed it seems intentional, how's that synchronization happening?

**Comment by sbespalov** [comment] 2020-05-05 04:00
The synchronization happening at `TestRepositoryManagementApplicationContext.tryToStart()` with `TestRepositoryManagementApplicationContext.lock()` method call.

**Comment by sbespalov** [comment] 2020-08-25 00:43
fixed

**Closed** 2020-08-25 00:43 UTC
Labels: ghc2020, hacktoberfest, help wanted, in progress, testing
